### PR TITLE
fix yoeo.names.yaml to yoeo_names.yaml

### PR DESCRIPTION
**Pull request by phinik**
## Proposed changes
Make naming scheme consistent between bitbots_vision and yoeo

## Related issues
https://github.com/bit-bots/YOEO/issues/93

### CODE REVIEW

**Review by jaagut — APPROVED** [review]

**Comment by phinik** [comment]
> Did we rename the files on data.bb?

What files do you mean?

**Comment by Flova** [comment]
Now the code expects the presence of a yoeo_names.yaml we therefore need to update the files on the server.

**Comment by phinik** [comment]
Are you referring to the changes in https://github.com/bit-bots/YOEO/pull/94 that solved https://github.com/bit-bots/YOEO/issues/93#issuecomment-1496395779? Cause this PR only touches @jaagut 's script which merely **creates** yoeo_names.yaml files.

**Comment by Flova** [comment]
Ahh nvm. I misread this.

**Pull request merged**
