### PR TITLE
Update Ubuntu CI

### PR DESCRIPTION
**Pull request by jaagut**
## Proposed changes
Updates and extends the CI:

- Runs on latest ubuntu
- Tests various python versions
- Uses dependency caching

## Necessary checks
- [ ] Update poetry package version [semantically](https://semver.org/)
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine

### CODE REVIEW

**Comment by jaagut** [comment]
TODOs:

- [ ] pip upgrade seems to not upgrade to the latest version (maybe dependent on python version matrix?)
- [ ] Investigate caching
- [ ] Activate test training and inferencing

**Comment by jaagut** [comment]
Where do we store config files for the CI? Do we create a working `/config/custom.data` or do we create a separate config in `/.github/workflows/` ?

**Comment by Flova** [comment]
For pytorchyolo we have a data config in the config folder. This points to a dummy custom dataset with one image as well as a label in the data folder. I would use this as the reference. We can maybe take the image from torso.

**Comment by Flova** [comment]
Otherwise nice PR

**Comment by Flova** [comment]
But I am not shure of we support python 3.6

**Comment by jaagut** [comment]
Other ideas:

- [ ] Test for determinism (training produces the same output?)
- [ ] Test conversion scripts

**Comment by jaagut** [comment]
Superseded by #94

**Pull request closed without merging**
